---
abstract: 'Pure Perl YAML Implementation'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YAML-Perl
no_index:
  directory:
    - inc
    - t
requires:
  Error: 0
  Filter::Util::Call: 0
  perl: 5.005003
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
